### ISSUE TITLE
archive-schema json not validating correctly

### ISSUE THREAD

**Issue by nikita-vanyasin** [opentok/OpenTok-PHP-SDK#117]
I am using PHP-SDK-2.2, pulled via composer.

During a request to startArchive I getting next exception:

   'The archiveJson provided is not valid. Errors:[createdAt] double value found, but an integer is required
[status] does not have a value in the enumeration Array
(
    [0] => available
    [1] => started
    [2] => stopped
    [3] => failed
    [4] => deleted
    [5] => uploaded
    [6] => expired
)

 archiveJson:Array
(
    [id] => myarchiveid
    [status] => paused
    [name] => record
    [reason] =>
    [sessionId] => mysessionid
    [partnerId] => mypartnerid
    [createdAt] => 1429700464000
    [size] => 0
    [duration] => 0
    [outputMode] => composed
    [hasAudio] => 1
    [hasVideo] => 1
    [sha256sum] =>
    [password] =>
    [updatedAt] => 1429701138000
    [url] =>
)
' in ....\vendor\opentok\opentok\src\OpenTok\Util\Validators.php:138

Obviously, schema is out of date.

**Comment by aoberoi** [comment]
thanks @nikita-vanyasin, i've created #119 to track this issue.
