### ISSUE TITLE
OpenTok\Archive not working with require 'opentok.phar' 

### ISSUE THREAD

**Issue by lrocher** [opentok/OpenTok-PHP-SDK#137]
An exception occur with OpenTok\Archive when using require  'opentok.phar'.
This exception not occur when using composer autoloading.
```
exception 'RuntimeException' with message 'Invalid input' in phar:///$$$/opentok.phar/vendor/aoberoi/json-works/src/JohnStevenson/JsonWorks/Document.php:167\nStack trace:
#0 phar:///$$$/opentok.phar/vendor/aoberoi/json-works/src/JohnStevenson/JsonWorks/Document.php(25): JohnStevenson\\JsonWorks\\Document->getInput(false, true, false)
#1 phar:///$$$/opentok.phar/src/OpenTok/Util/Validators.php(154): JohnStevenson\\JsonWorks\\Document->loadSchema(false)
#2 phar:///$$$/opentok.phar/src/OpenTok/Archive.php(101): OpenTok\\Util\\Validators::validateArchiveData(Array)
#3 phar:///$$$/opentok.phar/src/OpenTok/OpenTok.php(307): OpenTok\\Archive->__construct(Array, Array)
#4 /service.php(133): OpenTok\\OpenTok->startArchive('2_MX40NTAzNTUwM...', Array)
...
```
(Note: real path replaced by $$$)

It's look related to realpath usage in Utils/Validators.php returning false rather an expected path.
```
if (!self::$schemaUri) { self::$schemaUri = realpath(__DIR__.'/archive-schema.json'); } 
```

**Comment by aoberoi** [comment]
@lrocher thanks for point this one out.

it sounds like there are 2 related issues at play here:
*  `realpath()` is known to be buggy inside a phar
*  `__DIR__` is ambiguous inside a phar and the path may need to be specifically mounted using `Phar::mount()`

Here is a link that might be useful to resolve the first point: http://stackoverflow.com/a/20394796/305340

This one sounds a bit tricky, but I would be willing to accept pull requests to resolve this.

**Comment by lrocher** [comment]
I'm not a PHP expert but i'm not sure real_path() call is really required. 
__DIR__ normally return a valid absolute path without / at end. I looked code of Document::LoadSchema and it's call a file_get_contents with given file path.

For testing, i have rebuild opentok.phar file with 2 real_path call removed in Utils/Validators.php and it's work correctly.

**Comment by aoberoi** [comment]
@lrocher good point! according to [this answer](http://stackoverflow.com/questions/9415940/is-realpath-redundant-in-absolutepath-realpath-dir-is-dir-always), `realpath()` may just be redundant in this use. if you'd like to send your changes as a pull request, i'd be happy to test it out and merge.

**Comment by chrisribe** [comment]
Hello,

I am having the same issue, could someone please rebuild the opentok.phar file and push it to master. Current version of the file still generates this error.

Thanks

**Comment by chrisribe** [comment]
Rebuilt the phar file, I confirm this fixes the bug for me too.
https://github.com/chrisribe/OpenTok-PHP-SDK/tree/d97f83d44e5bf381d9f97e9988148d2c0353c5de

**Comment by aoberoi** [comment]
@chrisribe thanks for bringing this to my attention again today. i'll go ahead and merge and cut a new release.

**Comment by aoberoi** [comment]
release 2.3.1 is now available, and the issue is fixed.

**Comment by chrisribe** [comment]
Thanks a bunch !
