### ISSUE TITLE
Can't instantiate an interface in Error handling

### ISSUE THREAD

**Issue by davemun** [opentok/OpenTok-PHP-SDK#145]
https://github.com/opentok/OpenTok-PHP-SDK/blob/master/src/OpenTok/Util/Client.php#L188

I don't think this todo was completed. Falling into this catch all error produces its own error:

Fatal error: Cannot instantiate interface OpenTok\Exception\Exception in 
...../vendor/opentok/opentok/src/OpenTok/Util/Client.php 
on line 189

**Comment by aoberoi** [comment]
@davemun can you show me some code which triggers this error? i agree that the TODO still needs to be addressed, but in theory if we ever get to that point something unforeseen has gone wrong. i'd like to know what that unforeseen thing was.

**Comment by davemun** [comment]
Someone deployed to Google App Engine and tried to create a session. Reported to work fine on localhost.

**Comment by LoganLehman** [comment]
Here too on deleteArchive(). View this ticket #192

**Comment by aiham** [comment]
This was fixed on 12 August 2016 and should be included from v2.4.0 onwards: https://github.com/opentok/OpenTok-PHP-SDK/commit/d2a4bd6#diff-cd751004cbc618902aa02ae2aed35fbeL189 by referencing the global `\Exception` rather than the `Opentok\Exception\Exception`.
