### ISSUE TITLE
You must define an API_KEY and API_SECRET in the run-demo file

### ISSUE THREAD

**Issue by kamaljeets** [opentok/OpenTok-PHP-SDK#149]
I already did that but getting the issues
#!/bin/sh

if [ -z "$API_KEY"] || [-z "$API_SECRET" ] 

then
  export API_KEY=45611482
  export API_SECRET= 0123abcd
fi

if [ -d "cache" ]
then
  rm -rf cache/
fi

php -S localhost:8080 -t web web/index.php

**Comment by davemun** [comment]
I edited your issue - please don't expose your API secret to the public.

**Comment by davemun** [comment]
Are you following the instructions here? : https://github.com/opentok/OpenTok-PHP-SDK/tree/master/sample/Archiving#running-the-app

The entry point should be ./run-demo.

It sounds like you're trying to run the PHP web server directly instead.

**Comment by davemun** [comment]
From my comments above: I think this is user error.
