### ISSUE TITLE
OpenTok->listArchives() does not support filtering by session ID

### ISSUE THREAD

**Issue by jeffswartz** [opentok/OpenTok-PHP-SDK#172]
The OpenTok REST API now lets you filter by session ID when getting a list of archives: https://tokbox.com/developer/rest/#listing_archives. (You pass in a `sessionId` query parameter when calling the REST API method.) The `OpenTok->listArchives()` method in the OpenTok PHP SDK does not support this session ID filter.

**Comment by pthreat** [comment]
*bump* exactly. The listArchives method as it is currently designed implies you would need to do N/count requests to even get to the archives of a specific session.

**Comment by magroski** [comment]
Created PR #209 as a suggested fix

**Comment by msach22** [comment]
Released with 4.2.0
