### ISSUE TITLE
$ ../../composer.phar install not working in windows run command prompt  

### ISSUE THREAD

**Issue by divyasevenstar** [opentok/OpenTok-PHP-SDK#174]
Hello,

  I want to run Hello world project.  After installing composer in Hello world directory. One composer.phar file is generated then I will use above command in windows run command prompt then it is not working for me.

 Can you please help me to resolve this issue?

Thanks
 Divya

**Comment by aiham** [comment]
Please provide more details, particularly the error message you see and what version of PHP and the OpenTok PHP SDK you are using. Thanks

**Comment by Ragnorok-Gs** [comment]
Just enter the command without "../../" by typing plain "composer install".
I was facing the same problem read composer's manual and run the command with [composer install] and it worked just fine.

Hope it helps

**Comment by aiham** [comment]
Thanks @Rrak. Closing this issue now.
