### ISSUE TITLE
Does not support php 7

### ISSUE THREAD

**Issue by sourcebits-saurabh** [opentok/OpenTok-PHP-SDK#178]
- phpunit/phpunit 4.8.20 requires php ~5.3.3|~5.4|~5.5|~5.6 -> your PHP version (7.0.14) does not satisfy that requirement.
    - Conclusion: don't install sebastian/version 1.0.6
    - Conclusion: don't install phpunit/phpunit 4.8.34
    - Conclusion: don't install phpunit/phpunit 4.8.33
    - Conclusion: don't install phpunit/phpunit 4.8.32
    - Conclusion: don't install phpunit/phpunit 4.8.31
    - Conclusion: don't install phpunit/phpunit 4.8.30
    - Conclusion: don't install phpunit/phpunit 4.8.29
    - Conclusion: don't install phpunit/phpunit 4.8.28
    - Conclusion: don't install phpunit/phpunit 4.8.27
    - Conclusion: don't install phpunit/phpunit 4.8.26
    - Conclusion: don't install phpunit/phpunit 4.8.25
    - Conclusion: don't install phpunit/phpunit 4.8.24
    - Conclusion: don't install phpunit/phpunit 4.8.23
    - Conclusion: don't install phpunit/phpunit 4.8.22
    - Conclusion: don't install phpunit/phpunit 4.8.21
    - Conclusion: don't install phpunit/phpunit 4.8.19
    - Conclusion: don't install phpunit/phpunit 4.8.18
    - Conclusion: don't install phpunit/phpunit 4.8.17
    - Conclusion: don't install phpunit/phpunit 4.8.16
    - Conclusion: don't install phpunit/phpunit 4.8.15
    - Conclusion: don't install phpunit/phpunit 4.8.14
    - Conclusion: don't install phpunit/phpunit 4.8.13
    - Conclusion: don't install phpunit/phpunit 4.8.12
    - Conclusion: don't install phpunit/phpunit 4.8.11
    - Conclusion: don't install phpunit/phpunit 4.8.10
    - Conclusion: don't install phpunit/phpunit 4.8.9
    - Conclusion: don't install phpunit/phpunit 4.8.8
    - Conclusion: don't install phpunit/phpunit 4.8.7
    - Conclusion: don't install phpunit/phpunit 4.8.6
    - Conclusion: don't install phpunit/phpunit 4.8.5
    - Conclusion: don't install phpunit/phpunit 4.8.4
    - Conclusion: don't install phpunit/phpunit 4.8.3
    - Conclusion: don't install phpunit/phpunit 4.8.2
    - Conclusion: don't install phpunit/phpunit 4.8.1
    - Conclusion: don't install phpunit/phpunit 4.8.0
    - Conclusion: don't install phpunit/phpunit 4.7.7
    - Conclusion: don't install phpunit/phpunit 4.7.6
    - Conclusion: don't install phpunit/phpunit 4.7.5
    - Conclusion: don't install phpunit/phpunit 4.7.4
    - Conclusion: don't install phpunit/phpunit 4.7.3
    - Conclusion: don't install phpunit/phpunit 4.7.2
    - Conclusion: don't install phpunit/phpunit 4.7.1
    - Conclusion: don't install phpunit/phpunit 4.7.0
    - Conclusion: don't install phpunit/phpunit 4.6.10
    - Conclusion: don't install phpunit/phpunit 4.6.9
    - Conclusion: don't install phpunit/phpunit 4.6.8
    - Conclusion: don't install phpunit/phpunit 4.6.7
    - Conclusion: don't install phpunit/phpunit 4.6.6
    - Conclusion: don't install phpunit/phpunit 4.6.5
    - Conclusion: don't install phpunit/phpunit 4.6.4
    - Conclusion: don't install phpunit/phpunit 4.6.3
    - Conclusion: don't install phpunit/phpunit 4.6.2
    - Conclusion: don't install phpunit/phpunit 4.6.1
    - Conclusion: don't install phpunit/phpunit 4.6.0
    - Conclusion: don't install phpunit/phpunit 4.5.1
    - Conclusion: don't install phpunit/phpunit 4.5.0
    - Conclusion: don't install phpunit/phpunit 4.4.5
    - Conclusion: don't install phpunit/phpunit 4.4.4
    - Conclusion: don't install phpunit/phpunit 4.4.3
    - Conclusion: don't install phpunit/phpunit 4.4.2
    - Conclusion: don't install phpunit/phpunit 4.4.1
    - Conclusion: don't install phpunit/phpunit 4.4.0
    - Conclusion: don't install phpunit/phpunit 4.3.5
    - Conclusion: don't install phpunit/phpunit 4.3.4
    - Conclusion: don't install phpunit/phpunit 4.3.3
    - Conclusion: don't install phpunit/phpunit 4.3.2
    - Conclusion: don't install phpunit/phpunit 4.3.1
    - Conclusion: don't install phpunit/phpunit 4.3.0
    - Conclusion: don't install phpunit/phpunit 4.2.6
    - Conclusion: don't install phpunit/phpunit 4.2.5
    - Conclusion: don't install phpunit/phpunit 4.2.4
    - Conclusion: don't install phpunit/phpunit 4.2.3
    - Conclusion: don't install phpunit/phpunit 4.2.2
    - Conclusion: don't install phpunit/phpunit 4.2.1
    - Conclusion: don't install phpunit/phpunit 4.2.0
    - Conclusion: don't install phpunit/phpunit 4.1.6
    - Conclusion: don't install phpunit/phpunit 4.1.5
    - Conclusion: don't install phpunit/phpunit 4.1.4
    - Conclusion: don't install phpunit/phpunit 4.1.3
    - Conclusion: don't install phpunit/phpunit 4.1.2
    - Conclusion: don't install phpunit/phpunit 4.1.1
    - Conclusion: don't install sebastian/version 1.0.5
    - Installation request for phpunit/phpunit ~4.1 -> satisfiable by phpunit/phpunit[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.3.5, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.5.0, 4.5.1, 4.6.0, 4.6.1, 4.6.10, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.8.0, 4.8.1, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14, 4.8.15, 4.8.16, 4.8.17, 4.8.18, 4.8.19, 4.8.2, 4.8.20, 4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26, 4.8.27, 4.8.28, 4.8.29, 4.8.3, 4.8.30, 4.8.31, 4.8.32, 4.8.33, 4.8.34, 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8, 4.8.9].
    - Installation request for phing/phing dev-master -> satisfiable by phing/phing[dev-master].
    - phpunit/phpunit 4.1.0 requires sebastian/version ~1.0 -> satisfiable by sebastian/version[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].
    - Can only install one of: sebastian/version[2.0.0, 1.0.0].
    - Can only install one of: sebastian/version[2.0.0, 1.0.1].
    - Can only install one of: sebastian/version[2.0.0, 1.0.2].
    - Can only install one of: sebastian/version[2.0.0, 1.0.3].
    - Can only install one of: sebastian/version[2.0.0, 1.0.4].
    - phing/phing dev-master requires sebastian/version ^2.0 -> satisfiable by sebastian/version[2.0.0, 2.0.1].
    - Conclusion: don't install sebastian/version 2.0.1

**Comment by aiham** [comment]
Related #166

**Comment by aiham** [comment]
This should be resolved with v3
