### ISSUE TITLE
Extending classes is difficult

### ISSUE THREAD

**Issue by Hypnopompia** [opentok/OpenTok-PHP-SDK#212]
Since not all the possible API endpoints are yet implemented in this SDK, (signal session and list session streams are the two I currently need) it would be nice to be able to extend the `OpenTok\Util\Client` and `OpenTok\OpenTok` classes in order to implement them instead of having to fork the project and merge updates from upstream. However the necessary methods and properties in these classes are private instead of protected, so it makes extending them very difficult.

To extend the OpenTok class, the child class needs access to the `client` property. It's easy to pass in a custom client, but after that, I can't use it without keeping a reference to it somewhere.

To extend the Client class, the child class needs access to at least:
* `isDebug()`
* `handleException()`
* and the other exception handling methods.

**Comment by SecondeJK** [comment]
I'm going to close this as we are moving towards the OpenTok SDK being refactored to use the Vonage Comms API client class structure which is completely different (and inherited from Nexmo, not OpenTok). As this is the roadmap for our PHP kits, this library will eventually not be supported and we'll be encouraging developers to move to the more structurally complete core SDK.

**Comment by Hypnopompia** [comment]
@SecondeJK Where can I find the replacement PHP SDK? If it's not available yet, when will it be?
