### ISSUE TITLE
Recording in HD not working

### ISSUE THREAD

**Issue by nizamani** [opentok/OpenTok-PHP-SDK#229]
We are using OpenTok php SDK to do archiving, when I look at the documentation it says that we can set resolution property to `startArchive ` method but when I try following code it does not work and video still get archived in SD resolution i.e 648x480

```
// start video recording in HD and get archive id
$archive= $opentok->startArchive($session_id, array(
    'resolution' => '1280x720'
));
```

**Comment by msach22** [comment]
@nizamani Hmm that's interesting, could you please share which version of the PHP SDK you're using?

**Comment by nizamani** [comment]
We are currently using OpenTok version v4.0.0

**Comment by msach22** [comment]
Yes, that makes sense. HD archiving is only supported after v4.1.0. Please note that there was a `startArchive` bug in 4.1.0 so I recommend using `4.1.1`: https://github.com/opentok/OpenTok-PHP-SDK/releases/tag/v4.1.1

**Comment by nizamani** [comment]
Ok thanks I am checking 4.1.1

**Comment by msach22** [comment]
@nizamani If you want to get the latest features, I recommend upgrading to the latest PHP SDK!

**Comment by nizamani** [comment]
Yeah I will need to check what php version it supports since we are using Php 5.6

**Comment by msach22** [comment]
Sounds good. FYI, the latest SDK does support PHP 5.6

**Comment by nizamani** [comment]
Thank you I will update to latest SDK now :)
