### ISSUE TITLE
Issuer Not Found

### ISSUE THREAD

**Issue by VishalPurohitNRISI** [opentok/OpenTok-PHP-SDK#230]
When calling createSession from the PHP SDK, the call is returning the following error:
```
    Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: 
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <errorPayload>
    <code>-1</code>
    <message>Issuer not found</message>
    <description>Issuer not found</description>
```
This is I'm running on Windows Xampp php 7.1.16

**Comment by rogercbe** [comment]
Are you using the account API Key and Secret? We ran into the same problem by confusing project and account credentials. You will have to create a project and use the API Key and Secret from that project, not your global account credentials.

**Comment by msach22** [comment]
Thanks @rogercbe  - I've seen this happen a couple of times 😄 

@VishalPurohitNRISI I'm going to go ahead and close this issue due to inactivity, but please feel free to re-open if it still persists.
