### ISSUE TITLE
Automatically saving HD archives?

### ISSUE THREAD

**Issue by jlubeck** [opentok/OpenTok-PHP-SDK#231]
I'm using the automatic archiving of sessions and it's working great. But it seems like they only get saved in SD resolution. How can I make them save in HD?

This is how I'm creating the session:

```
        $sessionOptions = array(
            'archiveMode' => ArchiveMode::ALWAYS,
            'mediaMode' => MediaMode::ROUTED
        );
        $session = $opentok->createSession($sessionOptions);
```
Thank you!

**Comment by msach22** [comment]
@jlubeck Thanks for filing the issue. Unfortunately, at this time, the platform does not support auto archiving in HD, but I've gone ahead and relayed your request to our team.

**Comment by karljakober** [comment]
Bump +1 for this.
