### ISSUE TITLE
is there an endpoint for the session inspector ?

### ISSUE THREAD

**Issue by vesper8** [opentok/OpenTok-PHP-SDK#233]
I want to debug my sessions so I know where all my minutes are leaking from. Tokbox has this excellent inspector tool where you pass a session_id and get lots of useful information back.

Isn't there an API endpoint for this inspector tool ?

**Comment by msach22** [comment]
@vesper8 Apologies for missing this. We don't have an API to expose the session inspector logs, but we've recently released an Insights API which you can use to get session data. It exposes information such as usage, quality, and error metrics: https://tokbox.com/developer/guides/insights/

It's currently in public beta so if you have any questions, please email: insightsbeta@tokbox.com
