### ISSUE TITLE
 Unknown SSL protocol error in connection to api.opentok.com:443 

### ISSUE THREAD

**Issue by Jagdeep-Sing** [opentok/OpenTok-PHP-SDK#234]
The SDK was working fine before 
it start generating following error now:

` Uncaught Guzzle\Http\Exception\CurlException: [curl] 35: Unknown SSL protocol error in connection to api.opentok.com:443  [url] https://api.opentok.com/session/create`

What is the issue here ? 
something related to Curl or SSL ?

**Comment by Jagdeep-Sing** [comment]
@msach22 @aoberoi  Can you Please help me on this ??

**Comment by Jagdeep-Sing** [comment]
Okay, its solved now, tokbox support helped me to figure it out 
First we verified the TLS version, is it v1.2.
for  this verification, we used this code:
https://gist.github.com/msach22/e8d6f28b9cadddb26072410601e82172
TLS version was right.

then we did the following changes and it works fine:

Open TCP port 443
Whitelist the following domains:
*.tokbox.com
*.opentok.com

Thanks.

**Comment by msach22** [comment]
Glad to hear that it worked @Jagdeep-Sing!
