### ISSUE TITLE
List Broadcast API

### ISSUE THREAD

**Issue by msach22** [opentok/OpenTok-PHP-SDK#241]
This is an API Proposal for the list broadcast API call.

## List Broadcasts
The platform allows you to get a list of all broadcasts. See [docs](https://tokbox.com/developer/rest/#get_info_broadcast).

We propose to add a new method for getting all broadcast information in a session. 

### `listBroadcasts()`

```php
// Get list of broadcasts
$broadcastList = $opentok->listBroadcasts();
$broadcastList->totalCount(); // total count
```

```php
// Get list of broadcasts by sessionId
$broadcastList = $opentok->listBroadcasts($sessionId);
$broadcastList->totalCount(); // total count
```

You can also use `offset` and `count` when retrieving the broadcasts list:
```php
$broadcastList = $opentok->listBroadcasts($offset=0, $count=null);
```

**Comment by SecondeJK** [comment]
Merged
