### ISSUE TITLE
Error archive

### ISSUE THREAD

**Issue by sonnlv** [opentok/OpenTok-PHP-SDK#243]
I get error message when startArchive? Help me. pls

An uncaught Exception was encountered

Type: OpenTok\Exception\ArchiveDomainException

Message: Client error: `POST https://api.opentok.com/v2/project/46312092/archive` resulted in a `409 Conflict` response: {"code":15008,"message":"Only routed sessions are allowed to initiate archives.","description":"Only routed sessions are (truncated...)

Filename: /var/www/html/tokbox-com.vn/application/vendor/opentok/opentok/src/OpenTok/Util/Client.php

**Comment by msach22** [comment]
@sonnlv Thanks for filing an issue. It looks like you're trying to start an archive, but you created the session with `mediaMode` set to `relayed.` Please note that you can only start the archive for `routed` sessions.

**Comment by megacarlossm** [comment]
I'm having the same problem with Routed Session.
