### ISSUE TITLE
How can I run the HellowWorld app on an hosted server?

### ISSUE THREAD

**Issue by Davidian34** [opentok/OpenTok-PHP-SDK#245]
When I open the the index.php file this is the result: "You must define an API_KEY and API_SECRET in the run-demo file", however my "run-demo" file is correctly edited in the one.com server!

I only need the API_KEY and API_SECRET, right?

Thanks!

**Comment by dragonmantank** [comment]
Unfortunately the sample in the repo assumes you are starting the demo using the `run-demo` file, not running the demo under a normal web server. If you are installing this one a shared host, you will need to either add an environment variable in your back-end, or edit the `index.php` file to add the credentials directly.
