### ISSUE TITLE
Bump minimal required version of PHP

### ISSUE THREAD

**Issue by odolbeau** [opentok/OpenTok-PHP-SDK#246]
According to [this page](https://www.php.net/supported-versions.php), php 5.x & 7.0 are not supported at all anymore.
Security support for php 7.1 will end before the end of this year.

**Would you consider bumping the minimal required version of PHP to 7.1?**
Concerned issues: #159 #161 

**Would you consider removing support for hhvm?**

(I can work on it if needed)

**Comment by dragonmantank** [comment]
Hello!

We've removed support for HHVM in `dev-master`, and will soon be dropping support for PHP 5.6 and 7.0 in an upcoming release (most likely 4.5 or 4.6, both of which should be coming out relatively soon).

At that time we'll provide support for:

* 7.1
* 7.2
* 7.3
* 7.4

and test against nightly. While 7.1 and 7.2 are also now technically EOL, we have an internal policy to support them as some major frameworks still support that far back. 

I'll close this ticket once we push a release out that drops the older support.

**Comment by rumeau** [comment]
Hello i've been working on upgrading our current application to PHP >= 7.2 running on Laravel 8. Therefore, PHP SDK have conflicts with Guzzle version on Laravel.

I'm currently using a forked version which adds support for PHP >= 7.2.5 on https://github.com/rumeau/OpenTok-PHP-SDK
I've also have a Draft PR (https://github.com/opentok/OpenTok-PHP-SDK/pull/269) for this but not sure if it's needed as @dragonmantank coments theres an upcoming release.

Anyway i'll have this PR draft around in case there's enough intereset on it. And work with the forked version.

**Comment by dragonmantank** [comment]
Hello! Sorry for the slowness on this, we had some other things pop up that required more hands-on and pulled us from the getting the PHP upgrade finished.

We are still working on this. Stage one is updating to PHP 7.2, after that we will be altering the SDK to support any PSR-18 or HTTPlug-compatible client, reducing the need for Guzzle specifically.

**Comment by dragonmantank** [comment]
We bumped the minimum supported version to PHP 7.2 as of release 4.6.0 (which also supports Guzzle 7 now as well). With the new changes we're also on better footing for supporting PHP 8.0 once it drops.

If there are any other issues with the minimum version bump, feel free to reopen this issue. Thanks!
