### ISSUE TITLE
Change the HttpClient implementation

### ISSUE THREAD

**Issue by odolbeau** [opentok/OpenTok-PHP-SDK#247]
Even if Guzzle does the job, a lot of library use [php-http/httplug](https://github.com/php-http/httplug) which allow end developers to choose the HTTP Client implementation (including guzzle).

More recently, symfony released [its http-client component](https://github.com/symfony/http-client), an easy to use implementation (which can be used with php-http/httplug if needed).

**Would you consider switching to symfony/http-client? To php-http/httplug?**
Concerned issues: #90 #109 #110

**Comment by dragonmantank** [comment]
The current plan is to support PSR-18 clients via `php-http/httplug`, like our `nexmo/client` library. This is being actively worked on for the next major release.

**Comment by SecondeJK** [comment]
I'm going to close this, as we are moving towards moving the OpenTok video server code into the comms APIs infrastructure/repos, which puts allowing the user to change the HTTP client (as we do in vonage-php-sdk-core) out of scope for this library
