### ISSUE TITLE
how to change hls video background color to white

### ISSUE THREAD

**Issue by kameskarthi** [opentok/OpenTok-PHP-SDK#263]
Hi,

I am integrating opentok broadcast using hls.

In the hls video, i need to remove black background color,

Please refer the attached screenshot
![screen](https://user-images.githubusercontent.com/34235611/81558793-f22dcd00-93ab-11ea-9c2e-145e9e022147.png)

How can i remove this black color?

**Comment by SecondeJK** [comment]
This is a client library question, please head to https://github.com/opentok/webrtc-js for help on this
