### ISSUE TITLE
Dial method for SIP interconnect not working

### ISSUE THREAD

**Issue by qwertynik** [opentok/OpenTok-PHP-SDK#268]
```
$sessionId = "";
$token = "";
//Details.
$sipUri = "sip:1201xx47xxx@sip.nexmo.com;transport=tls";
$options = [
  'auth' => [
    "username" => 'zZzZ',
    "password" => 'xXxX',
  ],
  'secure' => true,
];
$call = $opentok->dial($sessionId, $token, $sipUri, $options);
```

I want to call my mobile phone number using the SIP endpoint of the Nexmo phone number. I am receiving a `200` OK response. However, the call does **not** link with the meeting. Neither am I receiving a phone call. Tried using the number for direct calling using Nexmo's API code. It works. So, not sure what is failing here.

Additionally, just while getting it to work, it changed the password to an incorrect one and it still sends me a 200 OK response with the `sessionId` and the `connectionId`.

**Comment by SecondeJK** [comment]
This sounds like it's a problem with engineering (the API side) as it's their call with how the API behaves. The library is only wrapping calls and responses. Regarding API behaviour, this would be one to raise as a ticket in OpenTok
