### ISSUE TITLE
validateLayoutClassList does not allow an empty array

### ISSUE THREAD

**Issue by psalt21** [opentok/OpenTok-PHP-SDK#270]
`validateLayoutClassList` checks to see if an array is associative using `Validators::isAssoc`. This method was based on an [outdated StackOverflow answer](https://stackoverflow.com/revisions/173479/1) that would incorrectly return true on an empty array. 

Because of this it is impossible to call `updateStream` with an empty `layoutClassList`. The `isAssoc` helper should be updated to the [corrected answer](https://stackoverflow.com/a/173479).

**Comment by SecondeJK** [comment]
fixed by #336, thank you!
