### ISSUE TITLE
PHP-FPM saturation

### ISSUE THREAD

**Issue by vegazrelli** [opentok/OpenTok-PHP-SDK#274]
We use your API on a web application that creates several sessions (meeting of 2 people) during an online speed business networking event. Each users generates some call to our server to initiate the session, get the token etc..but seems that **PHP-FPM** process that manage these requests never ends. So, in the next meeting, each user needs another php process to initiate another session. In this way we get a saturation of the php-fpm processes. Any advice?

## Your Environment
* Version used: 4.4.1
* PHP 7.4 on nginx 1.17.3
* Ubutnu 18.04.5 LTS

**Comment by dragonmantank** [comment]
Would you be able to share some of the code that you are using for this? PHP-FPM by itself just manages pools of processes so that a web server does not need to handle them, but each new HTTP request should get a fresh process. PHP-FPM doesn't change the fundamental way PHP starts and tears down requests so there should not be any inherent data sharing without explicit code.

**Comment by vegazrelli** [comment]
Here the code:

`function newSession() {
    ...
    $this->initializeOpenTok( $event->time_speed_match * 60 );
    $videoCall = VideoCall::updateOrCreate( [
        'event_id'        => $event->id,
        'user_id'         => Auth::user()->id ?? 0,
        'user_id_connect' => ''
    ], [
        'session_id' => $this->createSession(),
    ] );

    ...

    return response()->json( [
        'message' => $videoCall->session_id,
        'opz'     => 3,
        'data'    => [
            'user'         => Auth::user(),
            'user_connect' => $userConnect ?? []
        ]
    ], 200 );
}


function newToken() {
    ...
    $this->initializeOpenTok( $event->time_speed_match * 60 );
    $time = time() + ( $event->time_speed_match + 1 ) * 60;
    $token = $this->opentok->generateToken( $sessionId, [
        'role'                   => Role::PUBLISHER,
        'expireTime'             => $time,
        'data'                   => Auth::user()->name ?? 'Guest',
        'initialLayoutClassList' => [ 'focus-class-lit bestFit' ]
    ] );

    return response()->json( [
        'message' => $token
    ], 200 );
}


Other functions:


public function initializeOpenTok($timeout=300){
    $this->opentok = new OpenTok(env('VIDEO_API_KEY'), env('VIDEO_SECRET'), [
        'timeout' => $timeout
    ]);
}

public function createSession(){
    $session = $this->opentok->createSession();
    $sessionId = $session->getSessionId();

    return $sessionId;
}`

**Comment by dragonmantank** [comment]
I apologize, I think I may have misunderstood your question as more the same session IDs were being shared versus a process being hung.

Is it that, or is it that all the processes generated by PHP-FPM hang and the pool runs out of available processes? For example, you are getting `server reached pm.max_children setting` or similar errors?

**Comment by vegazrelli** [comment]
After some minutes (5/6, so after creating 10 session for 20 users), the server start to refuse new connections and it give me this type of error:

2020/11/11 13:06:51 [error] 29454#29454: *566 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: beta.clockmeet.com, request: "POST /it/events/DMRLNGxG/find-new-user HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock", host: "beta.clockmeet.com", referrer: "https://beta.clockmeet.com/it/events/XXXXXX/speed-match"

Seems like all the php-fpm processes are still managing the initial meetings, like sa if something is still going on...

**Comment by dragonmantank** [comment]
I would add some additional logging to see where the processes are hanging. Off-hand there isn't anything specifically blocking in our SDK, but without any additional PHP errors I wouldn't be able to provide much more clarification. I'm not ruling us out, but there's nothing specific to PHP-FPM and the SDK that would outright cause a hang.

If your framework has a logging mechanism I would start to add debug logs every few operations in your code, or start dropping `error_log()` calls after anything called to see if you can pinpoint where it hangs. If it is pretty consistent hopefully you can run it in a dev instance, but at this moment pinpointing exactly where it hangs is key.

**Comment by vegazrelli** [comment]
OK :-(

Thanks so much!!

**Comment by dragonmantank** [comment]
Closing. If you do find that we are actually causing the stalling somewhere in your code path, feel free re-open this issue and we'll see what we can do!
