### ISSUE TITLE
opentok/src/OpenTok/Util/Client.php - handleSignalingException sporadically causes another unhandled exception

### ISSUE THREAD

**Issue by Kaishiyoku** [opentok/OpenTok-PHP-SDK#276]
Inside the `/src/OpenTok/Util/Client.php:620` signalling exceptions are being handled by the `handleSignalingException` method. Iniside this method another unhandled exception is being thrown sporadically when the whole response is empty.

This is because on line 620 `$responseCode = $e->getResponse()->getStatusCode();` fails when getResponse() is NULL.

## Expected Behavior
The signal exception handler doesn't throw another unhandled exception.

My suggestion would be to check if the response object is NULL and if this is the cause handle that accordingly.

## Current Behavior

I get thousands of those exceptions every week, saying:

```
Error: Call to a member function getStatusCode() on null
 File "/vendor/opentok/opentok/src/OpenTok/Util/Client.php", line 620, in OpenTok\Util\Client::handleSignalingException
    $responseCode = $e->getResponse()->getStatusCode();
  File "/vendor/opentok/opentok/src/OpenTok/Util/Client.php", line 531, in OpenTok\Util\Client::signal
    $this->handleSignalingException($e);
  File "/vendor/opentok/opentok/src/OpenTok/OpenTok.php", line 819, in OpenTok\OpenTok::signal
    $this->client->signal($sessionId, $payload);

[...]
```

![phpstorm64_UBSqakaZYF](https://user-images.githubusercontent.com/5131112/99784687-7a8be800-2b1c-11eb-92c8-50477cefc475.png)

## Steps to Reproduce (for bugs)

I don't know what causes the response being empty but it should be handled anyway.

## Your Environment

* Version used: 4.5.0 (but also affects the latest version)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): PHP 7.4.8 on Docker php-fpm
* Operating System and version: Latest version of Windows 10

**Comment by dragonmantank** [comment]
As near as I can tell, the only way there there is no response is if some other type of error is happening during the connection back to us. After some testing the only way I could get an exception at that point in the code was if there was no response back from the server, indicating either an issue connecting to us in the first place or some timeout. 

I added some tighter exception handling around the signal request, so hopefully that will help out. That code is currently going through review, but if you would like to test it early you can update to that code with:

```console
composer require opentok/opentok:dev-bug/276-improper-handling-of-signal-failures@dev
```

You can switch back to a stable branch with:

```console
composer require opentok/opentok:^4.5
```

Once a release goes out I will let you know via this issue.
