### ISSUE TITLE
ClientTest.php causes a Composer deprecation notice when updating opentok/opentok

### ISSUE THREAD

**Issue by Kaishiyoku** [opentok/OpenTok-PHP-SDK#280]
When I update to v4.6.2 with Composer v1 I get the following deprecation notice:

> Deprecation Notice: Class OpenTokTest\Util\ClientTest located in ./vendor/opentok/opentok/tests/OpenTokTest/Utils/ClientTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

## Expected Behavior
* no deprecation notice/working with Composer v2

## Current Behavior
* deprecation notice when running `composer update`

## Possible Solution
/

## Steps to Reproduce (for bugs)
1. download a v1 composer.phar
2. run `composer init`
3. run `composer require opentok/opentok`
4. deprecation notice will appear

## Context
/

## Your Environment
* Version used: 4.6.2
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): PHP 7.4.15
* Operating System and version: Windows 10

**Comment by dragonmantank** [comment]
Thanks for the tip! I just submitted a PR to cover this (at some point the folder was named `Utils` instead of `Util`). This shouldn't have affected any actual running code since the tests are used exclusively by phpunit. I'll close this out once the PR has been merged.
