### ISSUE TITLE
Invalid stream object

### ISSUE THREAD

**Issue by TheDATech** [opentok/OpenTok-PHP-SDK#308]
I want to init browser-to-browser audio call but I got some invalid object in console.
```
OT_INVALID_PARAMETER: Session.subscribe :: invalid stream object +0msOpenTok:GlobalExceptionHandler:error 
OT.exception :: title: Unable to Subscribe (1501) msg: Session.subscribe :: invalid stream object
```

Here is the piece of code of my script:

```
      // Setting an audio source to a new MediaStreamTrack
      const stream = await OT.getUserMedia({
        videoSource: null
      });

      const [audioSource] = stream.getAudioTracks();
      publisher.setAudioSource(audioSource).then(() => console.log('Audio source updated'));
      subscriber = session.subscribe(stream, targetElement, options);
```

I've init the publisher, connected to the session but still getting this invalid in console.

I'm using Laravel 9 in windows. and here is the link of of script:
https://github.com/TheDATech/gharyal/blob/master/resources/views/layouts/app.blade.php

**Comment by SecondeJK** [comment]
This is all client side JS, so as a result I think it's a fair conclusion to say this bug will need to be raised with the OpenTok JS Client - the backend isn't throwing the error, the client and OpenTok servers are.
