### ISSUE TITLE
Screenshare Dialogue box 

### ISSUE THREAD

**Issue by hamza-embelem** [opentok/OpenTok-PHP-SDK#310]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Operating System and version:

**Comment by hamza-embelem** [comment]
Can i get the chrome option first, instead of entire screen option for sharing screen.

**Comment by SecondeJK** [comment]
This appears to be a feature request for the frontend, rather than this specific library.
