### ISSUE TITLE
4.11.0 SIP dialing error

### ISSUE THREAD

**Issue by elblasto** [opentok/OpenTok-PHP-SDK#311]
The error that was mentioned in https://github.com/opentok/OpenTok-PHP-SDK/issues/298 still persists in v4.11.0
<img width="663" alt="Screenshot 2022-07-19 at 17 28 36" src="https://user-images.githubusercontent.com/3849725/179672110-95eabd14-dfa9-4796-9b27-eb1344d8e180.png">

Look like the result of the `dial` function in `src/OpenTok/Util/Client.php` doesn't contain `observeForceMute`. Here is an actual result `{"id":"f987b235-xxxx-xxxx-xxxx-6ce9b9afxxx","projectId":"4xxxxxx1","sessionId":"1_xxx-xx","connectionId":"767f3c08-xxxx-xxxx-xxxx-ed1d167977ab","streamId":"c2400de1-xxxx-xxxx-xxxx-df36175f14ee","createdAt":1658209134948,"updatedAt":1658209134948}`

**Comment by SecondeJK** [comment]
This was specifically asked to be added, so I'm going to assume that it's not been released yet. I'll merge #309 and this should resolve this and#298.
