### ISSUE TITLE
The apiKey was not a string nor an integerin laravel project

### ISSUE THREAD

**Issue by Namaty06** [opentok/OpenTok-PHP-SDK#324]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Operating System and version:

**Comment by SecondeJK** [comment]
Closing due to:
* Not enough information provided
* PHP5.4 is not supported by this library. I'd highly recommend tackling this big security problem first (PHP5.4 was End-of-life seven years ago)

**Comment by Namaty06** [comment]
can i have prices for api call !


Le mar. 7 févr. 2023 à 11:27, James Seconde ***@***.***> a
écrit :
