### ISSUE TITLE
v4.14.5: OT_AUTHENTICATION_ERROR: token has expired (1004)

### ISSUE THREAD

**Issue by garrettboone** [opentok/OpenTok-PHP-SDK#352]
Both sides of call have error showing `OT_AUTHENTICATION_ERROR: token has expired (1004)`

## Expected Behavior
Call connects fine.

## Current Behavior
When upgrading to 4.14.5 it breaks something for us, however if we downgrade to v4.14.4 our code works fine without new packages (sodium, jwt, etc)

Person A calls B. 
A's publisher is seen by B after subscription.
B's publisher is never seen by A, both sides have error.

## Environment
This behavior is seen in two systems:
1) Centos 7, php83, NGINX
2) WSL: Ubuntu `Linux 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

```
"Error: token has expired (1004)
    at onSessionInfoError (https://site.local/node_modules/.vite/deps/@opentok_client_dist_js_opentok__js.js?v=220147db:51486:55)
    at invokeCallback (https://site.local/node_modules/.vite/deps/@opentok_client_dist_js_opentok__js.js?v=220147db:424:31)
    at publish (https://site.local/node_modules/.vite/deps/@opentok_client_dist_js_opentok__js.js?v=220147db:413:23)
    at publishRejection (https://site.local/node_modules/.vite/deps/@opentok_client_dist_js_opentok__js.js?v=220147db:371:19)
    at MutationObserver.flush (https://site.local/node_modules/.vite/deps/@opentok_client_dist_js_opentok__js.js?v=220147db:227:21)"
```

Edit: I realize now this might not be the correct repo given the error details.

**Comment by dragonmantank** [comment]
If you are using Tokbox, this would be the correct repo. Let me get this fixed here in just a bit, there is an issue as Tokbox is switching to JWT client tokens.

**Comment by garrettboone** [comment]
> If you are using Tokbox, this would be the correct repo. Let me get this fixed here in just a bit, there is an issue as Tokbox is switching to JWT client tokens.

Yes that is correct regarding Tokbox

**Comment by dragonmantank** [comment]
v4.14.6 has been released which reverts this back to generating the older T1 style token. You should be able to switch this this now. Let me know if it gives you any issues.

**Comment by garrettboone** [comment]
I will test thanks!

**Comment by garrettboone** [comment]
@dragonmantank Yes v4.14.6 works!

**Comment by dragonmantank** [comment]
Great! tl;dr is that OpenTok is moving away from the older style T1 tokens to proper JWTs. Normally this wouldn't be an issue, but after this release was put out it turned out that the expiration isn't being handled properly in the API on the JWTs.

I thought we had rolled this package back but apparently had not. Sorry about the inconvenience!
