### ISSUE TITLE
Tokbox PHP SDK not build

### ISSUE THREAD

**Issue by liyifei1987** [opentok/OpenTok-PHP-SDK#65]
Hi,
I am developing video chat app using your opentok.
I tried to use your php server sdk from your git sample, but I cannot build it.
I don't understand "add this package 'opentok/opentok' to composer.json" .
I tried this: require: { "opentok/opentok" : "2.2.*" }
But my computer says "could not found any version of opentok/opentok".
What's wrong?
Could you help me how to use your sample on my server?
Thank you.
PS: I used the version 1.1 in my server and my web client app before.
But  the web client app(basictutorial.html from your version 1.1 sample, link:"http://tokbox.com/opentok/v1/tutorials/basic-tutorial/js/" : Download the source code section) says that the generated token is not valid.
I generated the token and session_id using the version 1.1 (apiObj = OpenTokSDK...)

Best Regards!

**Comment by deepak01230** [comment]
Hi Frnds ,
i am new to opentok and dont know how to get the open tok package in my project folder.
I have successfully run the composer it does not show the open tok folder to use.
Pls help me to resolve the problem ?

**Comment by aoberoi** [comment]
@deepak01230 please send an email to support@tokbox.com with a full description of your problem.
